# Generated by Django 4.1.7 on 2023-03-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.BigIntegerField()),
                ('Nombres', models.CharField(max_length=95)),
                ('Correo', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('Rol', models.CharField(max_length=2)),
                ('Telefono', models.BigIntegerField()),
                ('Contrasena', models.CharField(max_length=15)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='profiles')),
            ],
        ),
    ]
