# Generated by Django 4.1.7 on 2023-03-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=15)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Caracteristicas', models.TextField(blank=True, null=True)),
                ('Disponible', models.IntegerField()),
                ('Precio_base', models.DecimalField(decimal_places=3, max_digits=9)),
                ('Porcentaje_plataforma', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('Porcentaje_venta', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('Precio_calculado', models.DecimalField(decimal_places=3, max_digits=9)),
                ('material', models.CharField(blank=True, max_length=55, null=True)),
                ('Portada', models.ImageField(upload_to='portada')),
                ('Estado', models.BooleanField(default=False)),
                ('Genero', models.CharField(blank=True, max_length=3, null=True)),
                ('Imagenes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop_App.productimage')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='productimage',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_App.producto'),
        ),
    ]
