# Generated by Django 4.1.7 on 2023-03-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Imagenes',
        ),
        migrations.AddField(
            model_name='producto',
            name='Imagenes',
            field=models.ManyToManyField(blank=True, to='shop_App.productimage'),
        ),
    ]
