# Generated by Django 4.1.7 on 2023-03-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_App', '0002_remove_producto_imagenes_producto_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Precio_calculado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
