# Generated by Django 4.1.7 on 2023-03-08 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_App', '0003_alter_producto_precio_calculado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calificacion', models.IntegerField()),
                ('Comentario', models.TextField(max_length=355)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_App.producto')),
            ],
        ),
    ]
