# Generated by Django 4.1.7 on 2023-04-12 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_App', '0005_remove_producto_imagenes_alter_productimage_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
